[package]
name = "wc_rs_tester"
version = "0.1.0"
edition = "2024"

[dependencies]
wallet-core-rs = { git = "https://github.com/trustwallet/wallet-core.git", branch = "master" }
alloy-signer-local = { version = "1.0.9", features = ["mnemonic"] }
anyhow = "1.0.98"
